version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/
    ports:
      - 8001:80